### ISSUE TITLE
All integer columns that we use as database keys need to be sequences (serial data type)

### ISSUE THREAD

**Issue by shoshber** [debtcollective/parent#158]
dawn [9:43 AM]
good morning. under this link https://tools.debtsyndicate.org/dispute-tools the tools do not work
tools.debtsyndicate.org
Tools and Services — The Debt Collective
We are debtors and allies organizing to renegotiate and resist our debts. Alone, our debts are a burden. Together, they make us powerful.

dawn [9:44 AM]
uploaded and commented on this image: error on tools page 

I get this message.

<500 something went wrong>

Alex Marcondes [9:54 AM]
Hmm. I think this is a problem with migrating the DB the way we did it. @orlando we should just make that column serial instead of depending on a sequence.
Thursday or Friday can both work for me, just let me know when and I'll make myself available :)

orlando [9:58 AM]
Oh yeah that needs to be serial
Can you open a ticket for it @Alex Marcondes please? I won’t have my computer until the end of the day
All integer columns that we use as database keys need to be sequences (serial data type) (edited)

Alex Marcondes [10:07 AM]
Well we need to set the sequence to start at the largest I'd we import then.

**Comment by marcondag** [comment]
So the discussion around this was poorly worded. The column (`"Disputes".readable_id`) _is_ already backed by a sequence. The problem is that the sequence starts at 105. If you manually insert a dispute with the value of 106 for the `readable_id`, then the next dispute to get inserted will conflict on the readable_id. To prevent this clash, whenever we import the disputes we need to run something similar to the following after:

```sql
SELECT setval('readable_id_seq', (SELECT max(readable_id) FROM "Disputes"), false);
```

**Comment by orlando** [comment]
This is part of the import now (https://github.com/debtcollective/discourse-import/commit/610d2a2159884611e5a5bdb257fb279e48324d39) , and I ran the command in staging database
