### ISSUE TITLE
Community layout issues on mobile

### ISSUE THREAD

**Issue by orlando** [debtcollective/parent#249]
The are some issues with the header layout in the Community when browsing from a mobile device, these screenshots were taken from an iPhone 6s

![image.png](https://images.zenhubusercontent.com/55c91a544f7a08fbb7f43521/b8d01af6-de7a-4721-b0c4-584f4d83004f)

![image.png](https://images.zenhubusercontent.com/55c91a544f7a08fbb7f43521/1203eee4-bb04-4e82-b408-d644a1e52cef)

## Tasks

- [ ] Replicate the issue in mobile simulator
- [ ] Fix the issue and adjust the theme to work better on mobile

## Acceptance criteria

- User browsing from a mobile device, shouldn't see the issues described above.

**Comment by duranmla** [comment]
![localhost_3000_ iphone 5_se](https://user-images.githubusercontent.com/1425162/50400795-c6478280-0789-11e9-9b83-20c142d1c0b2.png)

While the image above is clearly not perfect, the issue that is described may be already resolved, I am currently downloading the emulator in order to double check that should work on phy devices too. 

Nevertheless, I do not want to spend time fixing a lot of the details around the community site if we are planning to make any major improvements, thus, let me know what you want to do here @orlando do we fix the details on the community site or are we going to make a bigger visual refactor?

Cheers
